/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aviator;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Random;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;



/**
 *
 * @author Onur
 */
public class Aviator extends javax.swing.JFrame {
    
    private double bakiye;
    private boolean oyunBasladimi = false;
    private double yatirilan;
    private int say;
    private double cekilecekzamann;
    private boolean cekilecekgirildimi;
    private boolean yatirildimi = false;
    
    /**
     * Creates new form Aviator
     */
    public Aviator() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        sonuc = new javax.swing.JLabel();
        parabas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bakiyemiktari = new javax.swing.JLabel();
        bakiyeyukle = new javax.swing.JButton();
        BaslatButton = new javax.swing.JButton();
        yatirilacakpara = new javax.swing.JTextField();
        bilgilendirme = new javax.swing.JLabel();
        durum = new javax.swing.JProgressBar();
        cekilecekzaman = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sonuclabeli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panel.setBackground(new java.awt.Color(51, 255, 255));

        sonuc.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        sonuc.setText("0");

        parabas.setText("Para Yatir");
        parabas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parabasActionPerformed(evt);
            }
        });

        jLabel2.setText("Bakiye:");

        bakiyemiktari.setText("0");

        bakiyeyukle.setText("Bakiye Ekle");
        bakiyeyukle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeyukleActionPerformed(evt);
            }
        });

        BaslatButton.setText("Oyunu Başlat");
        BaslatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaslatButtonActionPerformed(evt);
            }
        });

        bilgilendirme.setText(" ");

        jLabel1.setText("Yatırılacak Miktar");

        jLabel3.setText("Çekmek İstediğin zaman");

        sonuclabeli.setText(" ");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(bakiyeyukle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BaslatButton)
                        .addGap(65, 65, 65))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bakiyemiktari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(410, 410, 410))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bilgilendirme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sonuclabeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(84, 84, 84))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yatirilacakpara))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cekilecekzaman)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addComponent(parabas)))
                .addGap(72, 72, 72))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sonuclabeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(durum, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekilecekzaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yatirilacakpara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parabas))
                .addGap(18, 18, 18)
                .addComponent(bilgilendirme)
                .addGap(40, 40, 40)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bakiyemiktari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bakiyeyukle)
                    .addComponent(BaslatButton))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bakiyeyukleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeyukleActionPerformed
        double yuklenecek = Double.parseDouble(JOptionPane.showInputDialog("Yüklenecek Bakiye Miktarını Giriniz"));
        
        bakiye += yuklenecek; 
        bakiyemiktari.setText(Double.toString(bakiye));
    }//GEN-LAST:event_bakiyeyukleActionPerformed

    private void parabasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parabasActionPerformed
        
        try{
            yatirilan = Double.parseDouble(yatirilacakpara.getText());
            cekilecekzamann = Double.parseDouble(cekilecekzaman.getText());
            if(cekilecekgirildimi == false){
                if (yatirilan > 0){
                    if(!oyunBasladimi){
                        if(yatirilan <=  bakiye){
                            try{
                                if((Double.parseDouble(cekilecekzaman.getText()) >= 1.0) && (Double.parseDouble(cekilecekzaman.getText()) <= 10)){
                                    cekilecekzamann = Double.parseDouble(cekilecekzaman.getText());
                                    bakiye -= yatirilan;
                                    bakiyemiktari.setText(Double.toString(bakiye));
                                    bilgilendirme.setText(yatirilan + "TL oyuna basıldı Oyunu Başlatın.");
                                    bilgilendirme.setForeground(Color.green);
                                    cekilecekgirildimi = true;
                                    yatirildimi = true;
                                }
                                else{
                                    bilgilendirme.setText("Çekilecek X yerine 1.0 - 10.0 arasında değer girin");
                                    bilgilendirme.setForeground(Color.red);

                                }
                            }catch(NumberFormatException c){
                                bilgilendirme.setText("Çekilecek X yerine 1.0 - 10.0 arasında değer girin");
                            }

                        }
                        else{
                            bilgilendirme.setText("Yeterli Kadar Bakiyeniz Yok Lütfen Bakiye Yükleyin.");
                            bilgilendirme.setForeground(Color.red);
                        }
                    }
                    else{
                        bilgilendirme.setText("Oyun Şuan Oynanıyor Para Ekleyemezsiniz");
                        bilgilendirme.setForeground(Color.red);
                    }
                }
                else{
                    bilgilendirme.setText("Lütfen Geçerli Bir Yatırılacak Miktarı girin");
                    bilgilendirme.setForeground(Color.red);

                }
                
            }
            else{
                
                    bilgilendirme.setText("Zaten Para Yatırmışsınız");
                    bilgilendirme.setForeground(Color.red);
            }
            
        }
        catch(NumberFormatException a){
            bilgilendirme.setText("Eksik Değer Girişi");
            bilgilendirme.setForeground(Color.red);
        }
        catch(NullPointerException e){
            
        }
        
        
        
        
    }//GEN-LAST:event_parabasActionPerformed
    public void kazanmaSesi(){
        try {
                File file = new File("kazan.wav");
                Clip clip = AudioSystem.getClip();
                clip.open(AudioSystem.getAudioInputStream(file));
                clip.start();
         
               } catch (Exception e) {
                   
                System.err.println(e.getMessage());
        }
    }
    public void kaybetmeSesi(){
        try {
                File file = new File("kaybet.wav");
                Clip clip = AudioSystem.getClip();
                clip.open(AudioSystem.getAudioInputStream(file));
                clip.start();
         
               } catch (Exception e) {
                   
                System.err.println(e.getMessage());
        }
                
                
}
    
    private void BaslatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaslatButtonActionPerformed
        
        Timer timer = new Timer(20,null);
        Random random = new Random();
        durum.setValue(0);
        timer.restart();
        say = 0;
        oyunBasladimi = true;
        int sans = random.nextInt(0,10);
        
        sonuc.setText("Bekleniyor...");
        bilgilendirme.setText(" ");
        sonuclabeli.setText(" ");
        /*
        
        SwingWorker<Double,Double> swingWorker = new SwingWorker<Double, Double>(){
            @Override
            protected Double doInBackground() throws Exception {

                for(double i = 1.0; i < 2.0;i += 0.01){
                    deneme.setText(Double.toString(i));
                    Thread.sleep(50);
                }
                
                return true;
            }
            
        };
        swingWorker.execute();*/
        
        timer.addActionListener(new ActionListener(){
            
        @Override
        public void actionPerformed(ActionEvent e) {
                say++;
                durum.setValue(say);
                        
                        
                        
                if(durum.getValue() == 100){
                    timer.stop();
                    
                    double a = 0;
                    if (sans < 4){
                        for(a = 1.0; a <= random.nextDouble(1.0,1.5); a += 0.1){

                            sonuc.setText(Double.toString(a));

                        }
                        
                    }
                    else if (sans < 6 && sans > 4){
                        for(a = 1.0; a <= random.nextDouble(1.5,2.0); a += 0.1){

                            sonuc.setText(Double.toString(a));

                        }
                        
                    }
                    else if (sans == 8){
                        for(a = 1.0; a <= random.nextDouble(2.0,6.0); a += 0.1){

                            sonuc.setText(Double.toString(a));

                        }
                        
                    }
                    else if (sans == 9){
                        for(a = 1.0; a <= random.nextDouble(6.0,10.0); a += 0.1){

                            sonuc.setText(Double.toString(a));

                        }
                        
                    }
                    
                    if(yatirildimi){
                        if(a < cekilecekzamann){
                            sonuclabeli.setText("Uçacağı Yeri Yanlış Tahmin Ettin " + yatirilan + "TL Kaybettin");
                            sonuclabeli.setForeground(Color.red);
                            kaybetmeSesi();

                        }
                        else{
                            bakiye += yatirilan * cekilecekzamann;
                            bakiyemiktari.setText(Double.toString(bakiye));
                            sonuclabeli.setText("Kazandın Bakiyene " + yatirilan * cekilecekzamann + "TL Eklendi");
                            sonuclabeli.setForeground(Color.green);
                            kazanmaSesi();
                        }
                        
                    }
                    else{
                        sonuclabeli.setText("Bu Oyuna Para Yatırmadınız");
                        sonuclabeli.setForeground(Color.black);
                    }
                    yatirildimi = false;
                    cekilecekgirildimi = false;
                    oyunBasladimi = false;
                }
            }
                    
        });
        timer.start();
        
    }//GEN-LAST:event_BaslatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aviator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aviator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aviator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aviator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aviator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BaslatButton;
    private javax.swing.JLabel bakiyemiktari;
    private javax.swing.JButton bakiyeyukle;
    private javax.swing.JLabel bilgilendirme;
    private javax.swing.JTextField cekilecekzaman;
    private javax.swing.JProgressBar durum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel;
    private javax.swing.JButton parabas;
    private javax.swing.JLabel sonuc;
    private javax.swing.JLabel sonuclabeli;
    private javax.swing.JTextField yatirilacakpara;
    // End of variables declaration//GEN-END:variables
}
