/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Onur
 */
public class AnaPanel extends javax.swing.JFrame {
    public static Desktop desktop = Desktop.getDesktop();
    /**
     * Creates new form AnaPanel
     */
    public AnaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        youtube = new javax.swing.JButton();
        steamac = new javax.swing.JButton();
        discordac = new javax.swing.JButton();
        epicgamesac = new javax.swing.JButton();
        classroomac = new javax.swing.JButton();
        udemyac = new javax.swing.JButton();
        githubac = new javax.swing.JButton();
        devcac = new javax.swing.JButton();
        vscodeac = new javax.swing.JButton();
        translateac = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setText("  Hoşgeldin");

        youtube.setText("Youtube'yi aç");
        youtube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youtubeActionPerformed(evt);
            }
        });

        steamac.setText("Steam Aç");
        steamac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steamacActionPerformed(evt);
            }
        });

        discordac.setText("Discord Aç");
        discordac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discordacActionPerformed(evt);
            }
        });

        epicgamesac.setText("Epic Games Aç");
        epicgamesac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epicgamesacActionPerformed(evt);
            }
        });

        classroomac.setText("Classroom Aç");
        classroomac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classroomacActionPerformed(evt);
            }
        });

        udemyac.setText("Udemy Aç");
        udemyac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udemyacActionPerformed(evt);
            }
        });

        githubac.setText("GitHub Aç");
        githubac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubacActionPerformed(evt);
            }
        });

        devcac.setText("DevC Aç");
        devcac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devcacActionPerformed(evt);
            }
        });

        vscodeac.setText("Visual Studio Code Aç");
        vscodeac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vscodeacActionPerformed(evt);
            }
        });

        translateac.setText("Translate Aç");
        translateac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(steamac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(discordac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(devcac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(udemyac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(youtube, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(classroomac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vscodeac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(githubac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(translateac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(epicgamesac, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(youtube)
                    .addComponent(githubac)
                    .addComponent(classroomac)
                    .addComponent(translateac))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devcac)
                    .addComponent(discordac)
                    .addComponent(steamac)
                    .addComponent(udemyac))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vscodeac)
                    .addComponent(epicgamesac))
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void youtubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youtubeActionPerformed
        String url = "www.youtube.com";
        try {
            desktop.browse(new URI(url));
        } catch (URISyntaxException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_youtubeActionPerformed

    private void classroomacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classroomacActionPerformed
        String url = "www.classroom.google.com";
        try {
            desktop.browse(new URI(url));
        } catch (URISyntaxException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_classroomacActionPerformed

    private void translateacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateacActionPerformed
        String url = "https://translate.google.com.tr/";
        try {
            desktop.browse(new URI(url));
        } catch (URISyntaxException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_translateacActionPerformed

    private void githubacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubacActionPerformed
        String url = "www.github.com";
        try {
            desktop.browse(new URI(url));
        } catch (URISyntaxException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_githubacActionPerformed

    private void udemyacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udemyacActionPerformed
        String url = "www.udemy.com/course/sifirdan-ileri-seviyeye-komple-java-gelistirici-kursu/learn/lecture/8523496?start=0#overview";
        try {
            desktop.browse(new URI(url));
        } catch (URISyntaxException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_udemyacActionPerformed

    private void devcacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devcacActionPerformed
        File file = new File("C:\\Program Files (x86)\\Dev-Cpp\\devcpp.exe");
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_devcacActionPerformed

    private void epicgamesacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epicgamesacActionPerformed
        File file = new File("C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe");
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_epicgamesacActionPerformed

    private void discordacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discordacActionPerformed
        File file = new File("C:\\Users\\Onur\\AppData\\Local\\Discord\\app-1.0.9008\\Discord.exe");
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_discordacActionPerformed

    private void steamacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steamacActionPerformed
        File file = new File("C:\\Program Files (x86)\\Steam\\steam.exe");
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_steamacActionPerformed

    private void vscodeacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vscodeacActionPerformed
        
        File file = new File("C:\\Users\\Onur\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe");
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(AnaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vscodeacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classroomac;
    private javax.swing.JButton devcac;
    private javax.swing.JButton discordac;
    private javax.swing.JButton epicgamesac;
    private javax.swing.JButton githubac;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton steamac;
    private javax.swing.JButton translateac;
    private javax.swing.JButton udemyac;
    private javax.swing.JButton vscodeac;
    private javax.swing.JButton youtube;
    // End of variables declaration//GEN-END:variables
}
