/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.stokuygulamasi;

import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onur
 */
public class Stokekrani extends javax.swing.JFrame {
    
    public static DefaultListModel model = new DefaultListModel();
    
    /**
     * Creates new form Stokekrani
     */
    public Stokekrani(String isim) {
        initComponents();
        kullanici_listesi.setModel(model);
        
        Iterator it = Stokuygulamasi.kullanicilar.keySet().iterator();
        
        while (it.hasNext()){
            model.addElement(it.next());
        }
        isimm.setText(isim);
        this.setTitle("Yönetici Paneli");
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kullanici_listesi = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        uruntablosu = new javax.swing.JTable();
        isim = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sayin = new javax.swing.JLabel();
        isimm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ekle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        fiyatdegistir = new javax.swing.JButton();
        adetdegistir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        degistirilecek_isim = new javax.swing.JTextField();
        degistirilecek_miktar = new javax.swing.JTextField();
        degistirilecek_fiyat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel2.setText("Kullanıcılar:");

        jScrollPane2.setViewportView(kullanici_listesi);

        uruntablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün", "Fiyat", "Miktar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(uruntablosu);
        if (uruntablosu.getColumnModel().getColumnCount() > 0) {
            uruntablosu.getColumnModel().getColumn(0).setResizable(false);
            uruntablosu.getColumnModel().getColumn(1).setResizable(false);
            uruntablosu.getColumnModel().getColumn(2).setResizable(false);
        }

        sayin.setText("Sayın: ");

        isimm.setText("jLabel6");

        jLabel1.setText("Yapmak İstediğiniz İşlemi Seçiniz:");

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        fiyatdegistir.setText("Fiyat Değiştir");
        fiyatdegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyatdegistirActionPerformed(evt);
            }
        });

        adetdegistir.setText("Adet Değiştir");
        adetdegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adetdegistirActionPerformed(evt);
            }
        });

        jLabel3.setText("Değiştirilecek Ürünün Özellikleri ->");

        degistirilecek_isim.setFont(new java.awt.Font("Tempus Sans ITC", 2, 12)); // NOI18N
        degistirilecek_isim.setText("isim");
        degistirilecek_isim.setToolTipText("t");
        degistirilecek_isim.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        degistirilecek_isim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                degistirilecek_isimMouseClicked(evt);
            }
        });

        degistirilecek_miktar.setFont(new java.awt.Font("Tempus Sans ITC", 2, 12)); // NOI18N
        degistirilecek_miktar.setText("Miktar");
        degistirilecek_miktar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                degistirilecek_miktarMouseClicked(evt);
            }
        });

        degistirilecek_fiyat.setFont(new java.awt.Font("Tempus Sans ITC", 2, 12)); // NOI18N
        degistirilecek_fiyat.setText("Fiyat");
        degistirilecek_fiyat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                degistirilecek_fiyatMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 2, 12)); // NOI18N
        jLabel4.setText("(Gerekli Olanları Yazın)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sayin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isimm, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adetdegistir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(degistirilecek_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sil)
                                    .addComponent(ekle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(77, 77, 77))
                                    .addComponent(degistirilecek_isim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fiyatdegistir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(degistirilecek_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sayin)
                    .addComponent(isimm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(degistirilecek_isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(degistirilecek_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degistirilecek_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiyatdegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adetdegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(isim, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) uruntablosu.getModel();
        String eklenecek = degistirilecek_isim.getText();
        String fiyat = degistirilecek_fiyat.getText();
        String adet = degistirilecek_miktar.getText();
        if (degistirilecek_isim.getText().trim().equals("")||degistirilecek_isim.getText().trim().equals("isim")){
            JOptionPane.showMessageDialog(null, "Lütfen Ürün İsmini Giriniz", "Uyarı" , JOptionPane.WARNING_MESSAGE);
            
        }
        else{
            if (degistirilecek_fiyat.getText().trim().equals("")||degistirilecek_fiyat.getText().trim().equals("Fiyat")){
                JOptionPane.showMessageDialog(null, "Lütfen Fiyat Giriniz", "Uyarı" , JOptionPane.WARNING_MESSAGE);
                
            }
            else{
                if (degistirilecek_miktar.getText().trim().equals("")||degistirilecek_miktar.getText().trim().equals("Miktar")){
                    JOptionPane.showMessageDialog(null, "Lütfen Adet Giriniz", "Uyarı" , JOptionPane.WARNING_MESSAGE);
                    
                }
                else{
                    Object[] eklelan = {eklenecek,fiyat,adet};
                    model.addRow(eklelan);
                            
                }
            }
        }
    }//GEN-LAST:event_ekleActionPerformed

    private void degistirilecek_isimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degistirilecek_isimMouseClicked
        degistirilecek_isim.setText("");
    }//GEN-LAST:event_degistirilecek_isimMouseClicked

    private void degistirilecek_miktarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degistirilecek_miktarMouseClicked
        degistirilecek_miktar.setText("");
    }//GEN-LAST:event_degistirilecek_miktarMouseClicked

    private void degistirilecek_fiyatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degistirilecek_fiyatMouseClicked
        degistirilecek_fiyat.setText("");
    }//GEN-LAST:event_degistirilecek_fiyatMouseClicked

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        
        
        DefaultTableModel model = (DefaultTableModel) uruntablosu.getModel();
        model.removeRow(uruntablosu.getSelectedRow());
    }//GEN-LAST:event_silActionPerformed

    private void fiyatdegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyatdegistirActionPerformed
        
        
        
        DefaultTableModel model = (DefaultTableModel) uruntablosu.getModel();
        
        if(uruntablosu.getSelectedRow() != -1){
            String yeni = JOptionPane.showInputDialog("Yeni Fiyati giriniz");
        
            model.setValueAt(yeni,uruntablosu.getSelectedRow(),1);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Bir Ürün Seçiniz " , "Uyarı !" , JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_fiyatdegistirActionPerformed

    private void adetdegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adetdegistirActionPerformed
        
        
        
        DefaultTableModel model = (DefaultTableModel) uruntablosu.getModel();
        if(uruntablosu.getSelectedRow() != -1){
            String yeni = JOptionPane.showInputDialog("Yeni Adeti giriniz");
            model.setValueAt(yeni,uruntablosu.getSelectedRow(),2);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Bir Ürün Seçiniz " , "Uyarı !" , JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_adetdegistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        String a = "b";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stokekrani(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adetdegistir;
    private javax.swing.JTextField degistirilecek_fiyat;
    private javax.swing.JTextField degistirilecek_isim;
    private javax.swing.JTextField degistirilecek_miktar;
    private javax.swing.JButton ekle;
    private javax.swing.JButton fiyatdegistir;
    private javax.swing.JLabel isim;
    private javax.swing.JLabel isimm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> kullanici_listesi;
    private javax.swing.JLabel sayin;
    private javax.swing.JButton sil;
    private javax.swing.JTable uruntablosu;
    // End of variables declaration//GEN-END:variables
}
