/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ubs;

import static com.mycompany.ubs.OgrenciGirisi.dosya;
import static com.mycompany.ubs.Ubs.ogrencilerinisimleri;
import static com.mycompany.ubs.Ubs.ogretimelemanlari;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Onur
 */
public class OgretimUyesiGirisi extends javax.swing.JFrame {
    Iconlar iconlar = new Iconlar();
    static String ogretimuyesiismi;
    
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    public OgretimUyesiGirisi(String ogretimuyesiismi) {
        initComponents();
        
        this.setLocation(dim.width/2 - this.getSize().width/2, dim.height/2 - this.getSize().height/2);
        this.setResizable(false);
        this.ogretimuyesiismi = ogretimuyesiismi;
        
        jLabel3.setText(ogretimuyesiismi);
        
        try (BufferedReader br = new BufferedReader(new FileReader(dosya))) {
            String line;
            String duyuru = ""; 
            while ((line = br.readLine()) != null) {
                duyuru += line + "\n";
                
            }
                jTextArea1.setText(duyuru);
        } catch (IOException e) {
          e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        anapanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        genel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        ogrenciekle = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        isim = new javax.swing.JTextField();
        kullanici_adi = new javax.swing.JTextField();
        ekle_butoon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sifre = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        silinecek_id = new javax.swing.JTextField();
        sil_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        notlar = new javax.swing.JPanel();
        not_kullaniciadi = new javax.swing.JTextField();
        not_vize = new javax.swing.JTextField();
        not_button = new javax.swing.JButton();
        not_dersismi = new javax.swing.JTextField();
        not_final = new javax.swing.JTextField();
        Bilgi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        duyuruyayınla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        duyuruyayinla = new javax.swing.JTextArea();
        yayınla = new javax.swing.JButton();
        devamsızlık = new javax.swing.JPanel();
        devamsizlikgunu = new javax.swing.JSpinner();
        devamsizlikyapanid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dilekceler = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dilekceokualan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        anapanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel2.setIcon(iconlar.getOkulrenkli());
        jLabel2.setText(" ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("Öğrenci Kaydet");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("Notları Düzenle");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("Devamsızlıklar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("Duyuru Yayınla");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(iconlar.getCikrenkli());
        jLabel8.setText(" ");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("Dilekçeleri Oku");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        genel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setText("Hoşgeldin");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel3.setText("jLabel3");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Duyurular:");

        javax.swing.GroupLayout genelLayout = new javax.swing.GroupLayout(genel);
        genel.setLayout(genelLayout);
        genelLayout.setHorizontalGroup(
            genelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genelLayout.createSequentialGroup()
                .addGroup(genelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(genelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(genelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(genelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        genelLayout.setVerticalGroup(
            genelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(genelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel2.add(genel, "card2");

        ogrenciekle.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setLayout(null);

        isim.setBackground(new java.awt.Color(204, 255, 204));
        isim.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "İsim Soyisim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N
        jPanel7.add(isim);
        isim.setBounds(50, 280, 180, 60);

        kullanici_adi.setBackground(new java.awt.Color(204, 255, 204));
        kullanici_adi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kullanıcı Adı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N
        jPanel7.add(kullanici_adi);
        kullanici_adi.setBounds(50, 130, 180, 60);

        ekle_butoon.setText("Ekle");
        ekle_butoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butoonActionPerformed(evt);
            }
        });
        jPanel7.add(ekle_butoon);
        ekle_butoon.setBounds(100, 370, 72, 23);

        jLabel6.setIcon(iconlar.getAdduser());
        jLabel6.setText(" ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel7.add(jLabel6);
        jLabel6.setBounds(100, 170, 84, 80);

        jLabel5.setText(" ");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(6, 6, 272, 23);

        sifre.setBackground(new java.awt.Color(204, 255, 204));
        sifre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Şifre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N
        jPanel7.add(sifre);
        sifre.setBounds(50, 200, 180, 60);

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel8.setLayout(null);

        silinecek_id.setBackground(new java.awt.Color(255, 153, 153));
        silinecek_id.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kullanıcı Adı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N
        silinecek_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silinecek_idActionPerformed(evt);
            }
        });
        jPanel8.add(silinecek_id);
        silinecek_id.setBounds(80, 160, 151, 60);

        sil_button.setText("Sil");
        sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_buttonActionPerformed(evt);
            }
        });
        jPanel8.add(sil_button);
        sil_button.setBounds(110, 230, 90, 23);

        jLabel7.setIcon(iconlar.getRemoveuser());
        jLabel7.setText(" ");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel8.add(jLabel7);
        jLabel7.setBounds(110, 160, 80, 80);

        javax.swing.GroupLayout ogrenciekleLayout = new javax.swing.GroupLayout(ogrenciekle);
        ogrenciekle.setLayout(ogrenciekleLayout);
        ogrenciekleLayout.setHorizontalGroup(
            ogrenciekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ogrenciekleLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ogrenciekleLayout.setVerticalGroup(
            ogrenciekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(ogrenciekle, "card3");

        notlar.setBackground(new java.awt.Color(0, 204, 255));
        notlar.setLayout(null);

        not_kullaniciadi.setBackground(new java.awt.Color(0, 204, 255));
        not_kullaniciadi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kullanıcı Adı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N
        notlar.add(not_kullaniciadi);
        not_kullaniciadi.setBounds(330, 40, 180, 70);

        not_vize.setBackground(new java.awt.Color(0, 204, 255));
        not_vize.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vize Notu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N
        notlar.add(not_vize);
        not_vize.setBounds(330, 200, 180, 60);

        not_button.setText("Ekle");
        not_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                not_buttonActionPerformed(evt);
            }
        });
        notlar.add(not_button);
        not_button.setBounds(390, 360, 75, 30);

        not_dersismi.setBackground(new java.awt.Color(0, 204, 255));
        not_dersismi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ders İsmi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N
        not_dersismi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                not_dersismiActionPerformed(evt);
            }
        });
        notlar.add(not_dersismi);
        not_dersismi.setBounds(330, 120, 180, 60);

        not_final.setBackground(new java.awt.Color(0, 204, 255));
        not_final.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Final Notu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N
        notlar.add(not_final);
        not_final.setBounds(330, 280, 180, 60);

        Bilgi.setText(" ");
        notlar.add(Bilgi);
        Bilgi.setBounds(120, 350, 280, 16);

        jLabel10.setIcon(iconlar.getGrade());
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        notlar.add(jLabel10);
        jLabel10.setBounds(100, 110, 190, 190);

        jPanel2.add(notlar, "card4");

        duyuruyayınla.setBackground(new java.awt.Color(255, 204, 204));

        duyuruyayinla.setColumns(20);
        duyuruyayinla.setLineWrap(true);
        duyuruyayinla.setRows(5);
        duyuruyayinla.setWrapStyleWord(true);
        jScrollPane2.setViewportView(duyuruyayinla);

        yayınla.setText("Yayınla");
        yayınla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yayınlaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout duyuruyayınlaLayout = new javax.swing.GroupLayout(duyuruyayınla);
        duyuruyayınla.setLayout(duyuruyayınlaLayout);
        duyuruyayınlaLayout.setHorizontalGroup(
            duyuruyayınlaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duyuruyayınlaLayout.createSequentialGroup()
                .addGroup(duyuruyayınlaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(duyuruyayınlaLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(yayınla, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(duyuruyayınlaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        duyuruyayınlaLayout.setVerticalGroup(
            duyuruyayınlaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duyuruyayınlaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(yayınla)
                .addGap(100, 100, 100))
        );

        jPanel2.add(duyuruyayınla, "card5");

        devamsızlık.setBackground(new java.awt.Color(51, 255, 153));
        devamsızlık.setLayout(null);

        devamsizlikgunu.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1673056529417L), new java.util.Date(1704505920000L), java.util.Calendar.DAY_OF_YEAR));
        devamsizlikgunu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        devamsizlikgunu.setName(""); // NOI18N
        devamsızlık.add(devamsizlikgunu);
        devamsizlikgunu.setBounds(210, 270, 160, 50);

        devamsizlikyapanid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kullanıcı Adı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 2, 12))); // NOI18N
        devamsızlık.add(devamsizlikyapanid);
        devamsizlikyapanid.setBounds(210, 200, 160, 60);

        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        devamsızlık.add(jButton1);
        jButton1.setBounds(250, 340, 75, 23);

        jLabel9.setIcon(iconlar.getDevamsizlik());
        jLabel9.setText(" ");
        devamsızlık.add(jLabel9);
        jLabel9.setBounds(230, 50, 190, 140);

        jPanel2.add(devamsızlık, "card6");

        dilekceler.setBackground(new java.awt.Color(255, 204, 204));

        dilekceokualan.setEditable(false);
        dilekceokualan.setColumns(20);
        dilekceokualan.setRows(5);
        dilekceokualan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dilekçeler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N
        jScrollPane3.setViewportView(dilekceokualan);

        javax.swing.GroupLayout dilekcelerLayout = new javax.swing.GroupLayout(dilekceler);
        dilekceler.setLayout(dilekcelerLayout);
        dilekcelerLayout.setHorizontalGroup(
            dilekcelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dilekcelerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        dilekcelerLayout.setVerticalGroup(
            dilekcelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dilekcelerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.add(dilekceler, "card7");

        javax.swing.GroupLayout anapanelLayout = new javax.swing.GroupLayout(anapanel);
        anapanel.setLayout(anapanelLayout);
        anapanelLayout.setHorizontalGroup(
            anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anapanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        anapanelLayout.setVerticalGroup(
            anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(iconlar.getOkulrenksiz());
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(iconlar.getOkulrenkli());
    }//GEN-LAST:event_jLabel2MouseExited

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        kullanici_adi.setVisible(false);
        silinecek_id.setVisible(false);
        sil_button.setVisible(false);
        sifre.setVisible(false);
        isim.setVisible(false);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        ekle_butoon.setVisible(false);
        dilekceler.setVisible(false);
        ogrenciekle.setVisible(true);
        notlar.setVisible(false);
        duyuruyayınla.setVisible(false);
        devamsızlık.setVisible(false);
        genel.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
        ogrenciekle.setVisible(false);
        notlar.setVisible(true);
        duyuruyayınla.setVisible(false);
        devamsızlık.setVisible(false);
        dilekceler.setVisible(false);
        genel.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        
        ogrenciekle.setVisible(false);
        notlar.setVisible(false);
        duyuruyayınla.setVisible(false);
        devamsızlık.setVisible(true);
        dilekceler.setVisible(false);
        genel.setVisible(false);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        
        ogrenciekle.setVisible(false);
        notlar.setVisible(false);
        duyuruyayınla.setVisible(true);
        devamsızlık.setVisible(false);
        dilekceler.setVisible(false);
        genel.setVisible(false);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        genel.setVisible(true);
        
        try (BufferedReader br = new BufferedReader(new FileReader(dosya))) {
            String line;
            String duyuru = ""; 
            while ((line = br.readLine()) != null) {
                duyuru += line + "\n";
                
            }
                jTextArea1.setText(duyuru);
        } catch (IOException e) {
          e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_buttonActionPerformed
        if(Ubs.ogrenciler.containsKey(silinecek_id.getText())){

            Ubs.ogrenciler.remove(silinecek_id.getText());

            Ubs.ogrencilerinisimleri.remove(silinecek_id.getText());

            Set set = Ubs.ogrenciler.entrySet();
            Set set2 = Ubs.ogrencilerinisimleri.entrySet();

            Dosyalar.dosyayiTemizle();

            for(Iterator it = set.iterator(); it.hasNext();){
                Map.Entry entry = (Map.Entry) it.next();

                for(Iterator it2 = set2.iterator(); it2.hasNext();){
                    Map.Entry entry2 = (Map.Entry) it2.next();

                    Dosyalar.dosyayaYaz(Dosyalar.ogrenciFile,entry.getKey().toString(),entry.getValue().toString(),entry2.getValue().toString());
                    Ubs.ogrenciler.put(entry.getKey(), entry.getValue());
                    Ubs.ogrencilerinisimleri.put(entry.getKey(), entry2.getValue());silinecek_id.setVisible(true);
                    sil_button.setVisible(false);
                    jLabel7.setVisible(true);
                    silinecek_id.setVisible(false);
                    jLabel5.setText("Kullanıcı Başarı İle Silindi");
            jLabel5.setForeground(Color.green);

                }

            }

        }
        else{
            jLabel5.setText("Böyle Bir Kullanıcı Bulunmuyor");
            jLabel5.setForeground(Color.red);

        }
    }//GEN-LAST:event_sil_buttonActionPerformed

    private void ekle_butoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butoonActionPerformed

        if(!Ubs.ogrenciler.containsKey(kullanici_adi.getText()))
        if(!kullanici_adi.getText().equals("")){
            if(!sifre.getText().equals("")){
                if (!isim.getText().equals("")){

                    Dosyalar.dosyayaYaz(Dosyalar.ogrenciFile, kullanici_adi.getText(), sifre.getText(), isim.getText());
                    Ubs.ogrenciler.put(kullanici_adi.getText(), sifre.getText());
                    Ubs.ogrencilerinisimleri.put(kullanici_adi.getText(), isim.getText());

                    jLabel5.setText("Kullanıcı Başarıyla Kayıt Edildi");
                    jLabel5.setForeground(Color.green);
                    kullanici_adi.setVisible(false);
                    sifre.setVisible(false);
                    isim.setVisible(false);
                    ekle_butoon.setVisible(false);
                    jLabel6.setVisible(true);

                }
                else{
                    jLabel5.setText("İsim Alanını Boş Bırakamazsınız");
                    jLabel5.setForeground(Color.red);

                }
            }
            else{
                jLabel5.setText("Şifre Alanını Boş Bırakamazsınız");
                jLabel5.setForeground(Color.red);

            }
        }
        else{
            jLabel5.setText("Kullanıcı Adını Boş Bırakamazsınız");
            jLabel5.setForeground(Color.red);

        }
        else{

            jLabel5.setText("Böyle Bir Kullanıcı Zaten Bulunuyor");
            jLabel5.setForeground(Color.red);
        }

    }//GEN-LAST:event_ekle_butoonActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        kullanici_adi.setVisible(true);
        sifre.setVisible(true);
                    jLabel5.setText("");
        isim.setVisible(true);
        ekle_butoon.setVisible(true);
        jLabel6.setVisible(false);
        silinecek_id.setVisible(false);
        sil_button.setVisible(false);
        jLabel7.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(iconlar.getAdduserrenkli());
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(iconlar.getAdduser());
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(iconlar.getRemoveuserrenkli());
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(iconlar.getRemoveuser());
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        silinecek_id.setVisible(true);
        sil_button.setVisible(true);
        jLabel7.setVisible(false);
        kullanici_adi.setVisible(false);
        sifre.setVisible(false);
        jLabel5.setText("");
        isim.setVisible(false);
        ekle_butoon.setVisible(false);
        jLabel6.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void silinecek_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silinecek_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_silinecek_idActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
        Ubs ubs = new Ubs();
        ubs.setVisible(true);
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(iconlar.getCikrenksiz());
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(iconlar.getCikrenkli());
    }//GEN-LAST:event_jLabel8MouseExited

    private void yayınlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yayınlaActionPerformed
        
        StringBuilder builder = new StringBuilder();
        builder.append(duyuruyayinla.getText());
        
        Dosyalar.dosyayaYaz(Dosyalar.duyuruFile, builder.toString());
        
        
        
        
    }//GEN-LAST:event_yayınlaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Dosyalar.dosyayaYaz(Dosyalar.devamsizlikFile, devamsizlikyapanid.getText() ,devamsizlikgunu.getValue().toString());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void not_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_not_buttonActionPerformed
        String yer = "students/" + not_kullaniciadi.getText() + ".txt";
        //System.out.println(yer);
        File student = new File(yer);
        if(!student.exists()){
            try {
                student.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(OgretimUyesiGirisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (!not_kullaniciadi.getText().equals("")){
            if(!(not_dersismi.getText().equals(""))){
                if(not_final.getText().equals("") && not_vize.getText().equals("")){
                    Bilgi.setText("Lütfen Notları Giriniz");
                    Bilgi.setForeground(Color.red);

                }
                else if (not_final.getText().equals("") && !not_vize.getText().equals("")){
                        Dosyalar.dosyayaYaz(student, not_dersismi.getText(), not_vize.getText());
                        Bilgi.setText("Not Başarıyla Eklendi");
                        Bilgi.setForeground(Color.green);

                }
                else if (!not_final.getText().equals("") && !not_vize.getText().equals("")){

                    Dosyalar.dosyayaYaz(student, not_dersismi.getText(), not_vize.getText(),not_final.getText());
                        Bilgi.setText("Not Başarıyla Eklendi");
                        Bilgi.setForeground(Color.green);

                }
                else {

                    Bilgi.setText("Vize Notu Girilmeden Final Notu Girilemez");
                    Bilgi.setForeground(Color.red);
                }
                
            }
            else{
            Bilgi.setText("Lütfen Ders Adı Giriniz");
                Bilgi.setForeground(Color.red);
                
            }
        }
        else{
            Bilgi.setText("Lütfen Kullanıcı Adı Giriniz");
                Bilgi.setForeground(Color.red);
        }
        
        
        
    }//GEN-LAST:event_not_buttonActionPerformed

    private void not_dersismiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_not_dersismiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_not_dersismiActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setIcon(iconlar.getGradeunr());
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setIcon(iconlar.getGrade());
    }//GEN-LAST:event_jLabel10MouseExited

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        
        ogrenciekle.setVisible(false);
        notlar.setVisible(false);
        duyuruyayınla.setVisible(false);
        devamsızlık.setVisible(false);
        dilekceler.setVisible(true);
        genel.setVisible(false);
        
        try (BufferedReader br = new BufferedReader(new FileReader(Dosyalar.dilekceFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("=");
                String key = parts[0];
                String value = parts[1];
                value.replace("\n", "");
                String dilekce = key + "->>\n-----------------------------------\n" + value + "\n-----------------------------------\n\n";
                dilekceokualan.append(dilekce);
            }
        } catch (IOException e) {
          e.printStackTrace();
        }
        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgretimUyesiGirisi(ogretimuyesiismi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bilgi;
    private javax.swing.JPanel anapanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner devamsizlikgunu;
    private javax.swing.JTextField devamsizlikyapanid;
    private javax.swing.JPanel devamsızlık;
    private javax.swing.JPanel dilekceler;
    private javax.swing.JTextArea dilekceokualan;
    private javax.swing.JTextArea duyuruyayinla;
    private javax.swing.JPanel duyuruyayınla;
    private javax.swing.JButton ekle_butoon;
    private javax.swing.JPanel genel;
    private javax.swing.JTextField isim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JButton not_button;
    private javax.swing.JTextField not_dersismi;
    private javax.swing.JTextField not_final;
    private javax.swing.JTextField not_kullaniciadi;
    private javax.swing.JTextField not_vize;
    private javax.swing.JPanel notlar;
    private javax.swing.JPanel ogrenciekle;
    private javax.swing.JTextField sifre;
    private javax.swing.JButton sil_button;
    private javax.swing.JTextField silinecek_id;
    private javax.swing.JButton yayınla;
    // End of variables declaration//GEN-END:variables
}
